import React, { useState } from 'react';
import { 
  X, 
  Download, 
  FileText, 
  Star, 
  Share2, 
  Copy, 
  Check, 
  Sparkles, 
  Calendar, 
  Clock, 
  ShieldCheck, 
  MessageSquare
} from 'lucide-react';
import { SessionHistoryItem, AppSettings } from '../types';

interface SessionReviewModalProps {
  session: SessionHistoryItem | null;
  isOpen: boolean;
  onClose: () => void;
  settings: AppSettings;
}

export const SessionReviewModal: React.FC<SessionReviewModalProps> = ({
  session,
  isOpen,
  onClose,
  settings,
}) => {
  const [copied, setCopied] = useState<boolean>(false);
  const [userRating, setUserRating] = useState<number>(session?.rating || 5);
  const [feedbackNotes, setFeedbackNotes] = useState<string>(session?.notes || '');

  if (!isOpen || !session) return null;

  const handleCopyTranscript = () => {
    const text = session.fullTranscript.map(t => `[${t.time}] ${t.speaker}: ${t.text}`).join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTranscript = () => {
    const transcriptText = `SIGNLINK INTERPRETATION SESSION TRANSCRIPT
Title: ${session.title}
Date: ${session.date} | Duration: ${session.duration} | Dialect: ${session.language}
${session.interpreterName ? `Certified Interpreter: ${session.interpreterName}` : 'Mode: AI Real-Time Video Vision'}
Summary: ${session.summary}
Key Terminology: ${session.keyTerms.join(', ')}

=======================================
CONVERSATION TRANSCRIPT:
=======================================
${session.fullTranscript.map(t => `[${t.time}] ${t.speaker}: ${t.text}`).join('\n')}

Generated by SignLink AI & Video Interpretation Suite
`;

    const blob = new Blob([transcriptText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${session.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-transcript.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl relative p-6 sm:p-8">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-full text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header Badges */}
        <div className="flex items-center space-x-2 text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider mb-2">
          <FileText className="w-4 h-4" />
          <span>Session Review & Full Transcript</span>
        </div>

        {/* Title */}
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white pr-8">
          {session.title}
        </h2>

        {/* Metadata stats */}
        <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500 dark:text-slate-400 mt-2 font-medium">
          <span className="flex items-center space-x-1">
            <Calendar className="w-3.5 h-3.5 text-indigo-500" />
            <span>{session.date}</span>
          </span>
          <span>•</span>
          <span className="flex items-center space-x-1">
            <Clock className="w-3.5 h-3.5 text-indigo-500" />
            <span>{session.duration}</span>
          </span>
          <span>•</span>
          <span className="px-2 py-0.5 rounded bg-indigo-50 dark:bg-indigo-900/50 text-indigo-700 dark:text-indigo-300 font-bold">
            {session.language}
          </span>
          {session.interpreterName && (
            <>
              <span>•</span>
              <span className="flex items-center space-x-1 text-purple-600 dark:text-purple-300 font-bold">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>{session.interpreterName}</span>
              </span>
            </>
          )}
        </div>

        {/* Summary Card */}
        <div className="my-5 p-4 rounded-2xl bg-indigo-50/60 dark:bg-indigo-950/40 border border-indigo-200/60 dark:border-indigo-900">
          <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-900 dark:text-indigo-300 block mb-1 flex items-center space-x-1">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Session Summary & Action Items</span>
          </span>
          <p className="text-xs sm:text-sm text-slate-800 dark:text-slate-200 leading-relaxed">
            {session.summary}
          </p>
        </div>

        {/* Key Terms */}
        <div className="mb-5">
          <span className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider block mb-2">
            Identified Key Terminology
          </span>
          <div className="flex flex-wrap gap-1.5">
            {session.keyTerms.map((term, idx) => (
              <span
                key={idx}
                className="px-2.5 py-1 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300"
              >
                {term}
              </span>
            ))}
          </div>
        </div>

        {/* Full Conversational Transcript Stream */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2.5">
            <span className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
              Dialogue Breakdown ({session.fullTranscript.length} lines)
            </span>
            <div className="flex items-center space-x-1">
              <button
                onClick={handleCopyTranscript}
                className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 flex items-center space-x-1 transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
              <button
                onClick={handleDownloadTranscript}
                className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white flex items-center space-x-1 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export TXT</span>
              </button>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700 space-y-3 max-h-[220px] overflow-y-auto">
            {session.fullTranscript.map((t, idx) => (
              <div key={idx} className="text-xs">
                <div className="flex items-center space-x-2 mb-0.5">
                  <span className={`font-bold px-1.5 py-0.2 rounded text-[10px] ${
                    t.speaker === 'Signer'
                      ? 'bg-indigo-100 dark:bg-indigo-900/60 text-indigo-700 dark:text-indigo-300'
                      : t.speaker === 'Interpreter'
                      ? 'bg-purple-100 dark:bg-purple-900/60 text-purple-700 dark:text-purple-300'
                      : t.speaker === 'AI'
                      ? 'bg-cyan-100 dark:bg-cyan-900/60 text-cyan-700 dark:text-cyan-300'
                      : 'bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-200'
                  }`}>
                    {t.speaker}
                  </span>
                  <span className="text-[10px] text-slate-400 font-mono">{t.time}</span>
                </div>
                <p className="text-slate-800 dark:text-slate-200 pl-1 leading-relaxed">
                  {t.text}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Rating & Notes */}
        <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <span className="text-xs font-bold text-slate-800 dark:text-slate-200 block mb-1">
              Rate Session Quality
            </span>
            <div className="flex items-center space-x-1">
              {[1, 2, 3, 4, 5].map((star) => (
                <button
                  key={star}
                  onClick={() => setUserRating(star)}
                  className="p-1 hover:scale-110 transition-transform"
                >
                  <Star className={`w-5 h-5 ${
                    star <= userRating 
                      ? 'text-amber-400 fill-current' 
                      : 'text-slate-300 dark:text-slate-600'
                  }`} />
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs shadow-md shadow-indigo-500/25 transition-all"
          >
            Done & Save Review
          </button>
        </div>

      </div>
    </div>
  );
};
